version: '3.9'
services:
  app:
    build: .
    container_name: autoCred
    image: golang:1.19
    working_dir: /usr/src/autoCred
    command: go run github.com/pilu/fresh
    restart: on-failure
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - host
    volumes:
      - .:/usr/src/autoCred
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:14
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    expose:
      - '${DB_PORT}'
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    #    --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis:/data

volumes:
  postgres:
    driver: local
  redis:
    driver: local

networks:
  host:
    name: ${DB_HOST}
    external: true
