-- INSERT INTO working_activities (title) VALUES ('Пенсионер');
-- INSERT INTO working_activities (title) VALUES ('Работающий пенсионер');
-- INSERT INTO working_activities (title) VALUES ('Военнослужащий');
-- INSERT INTO working_activities (title) VALUES ('Игорный бизнес/Развлекательная индустрия');
-- INSERT INTO working_activities (title) VALUES ('Ресторан/Кафе/Бары');
-- INSERT INTO working_activities (title) VALUES ('Туризм');
-- INSERT INTO working_activities (title) VALUES ('Реклама');
-- INSERT INTO working_activities (title) VALUES ('Салон красоты');
-- INSERT INTO working_activities (title) VALUES ('Строительтво/Монтажные работы');
-- INSERT INTO working_activities (title) VALUES ('Розничная торговля');
-- INSERT INTO working_activities (title) VALUES ('Оптовая торговля');
-- INSERT INTO working_activities (title) VALUES ('Пищевая/легкая промышленность');
-- INSERT INTO working_activities (title) VALUES ('Снабжение');
-- INSERT INTO working_activities (title) VALUES ('Издательская деятельность');
-- INSERT INTO working_activities (title) VALUES ('Растениеводство');
-- INSERT INTO working_activities (title) VALUES ('Животноводство');

INSERT INTO working_activities (title) VALUES ('Пенсионер');
INSERT INTO working_activities (title) VALUES ('Работающий пенсионер');
INSERT INTO working_activities (title) VALUES ('Военнослужащий');
INSERT INTO working_activities (title) VALUES ('Сельское, лесное и рыбное хозяйство');
INSERT INTO working_activities (title) VALUES ('Горнодобывающая промышленность и разработка карьеров');
INSERT INTO working_activities (title) VALUES ('Обрабатывающая промышленность');
INSERT INTO working_activities (title) VALUES ('Снабжение электроэнергией, газом, паром, горячей водой и  кондиционированным воздухом');
INSERT INTO working_activities (title) VALUES ('Водоснабжение; сбор, обработка и удаление отходов, деятельность по ликвидации загрязнений');
INSERT INTO working_activities (title) VALUES ('Строительство');
INSERT INTO working_activities (title) VALUES ('Оптовая и розничная торговля; ремонт автомобилей и мотоциклов');
INSERT INTO working_activities (title) VALUES ('Транспорт и складирование');
INSERT INTO working_activities (title) VALUES ('Предоставление услуг по проживанию и питанию');
INSERT INTO working_activities (title) VALUES ('Информация и связь');
INSERT INTO working_activities (title) VALUES ('Финансовая и страховая деятельность');
INSERT INTO working_activities (title) VALUES ('Операции с недвижимым имуществом');
INSERT INTO working_activities (title) VALUES ('Профессиональная, научная и техническая деятельность');
INSERT INTO working_activities (title) VALUES ('Деятельность в области административного и вспомогательного обслуживания');
INSERT INTO working_activities (title) VALUES ('Государственное управление и оборона; обязательное  социальное обеспечение');
INSERT INTO working_activities (title) VALUES ('Образование');
INSERT INTO working_activities (title) VALUES ('Здравоохранение и социальное обслуживание населения');
INSERT INTO working_activities (title) VALUES ('Искусство, развлечения и отдых');
INSERT INTO working_activities (title) VALUES ('Предоставление прочих видов услуг');
INSERT INTO working_activities (title) VALUES ('Деятельность домашних хозяйств, нанимающих домашнюю прислугу; деятельность домашних хозяйств по производству товаров и услуг для собственного потребления');
INSERT INTO working_activities (title) VALUES ('Деятельность экстерриториальных организаций и органов');
